version: '2'
services:
  pacman:
    build: pacman/
    hostname: pacman
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pacman-data:/var/www/html/sites/
    environment:
      IRODS_FRONTEND_ENV_VIRTUAL_HOST: frontend.${RIT_ENV}.rit.unimaas.nl
      IRODS_HOST: irods
      IRODS_ENV_RODS_PASSWORD: irods
      DWH_FRONTEND_ENV_VIRTUAL_HOST: dwh.${RIT_ENV}.rit.unimaas.nl
      CROSSREF_LOOKUP_HOST: crossref-lookup
      VIRTUAL_HOST: pacman.${RIT_ENV}.rit.unimaas.nl
      OLS_URL: http://ols.tst.rit.unimaas.nl
      LOGSTASH_TAGS: PACMAN
      JWT_SECRET: foobar
networks:
  oculus_default:
    external: true
  common_default:
    external: true
volumes:
  pacman-data: 
    external: true
