version: '2'
services:
  pacman:
    build: pacman/
    hostname: pacman
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pacman-handsontable-data:/var/www/html/sites/all/modules/handsontable
      - pacman-islandora_ontology_autocomplete-data:/var/www/html/sites/all/modules/islandora_ontology_autocomplete
      - pacman-islandora_crossref_lookup-data:/var/www/html/sites/all/modules/islandora_crossref_lookup
      - pacman-pacman-data:/var/www/html/sites/all/modules/pacman
      - pacman-rit_landing_page-data:/var/www/html/sites/all/modules/rit_landing_page
      - pacman-rit_forms-data:/var/www/html/sites/all/modules/rit_forms
      - pacman-rit_faker-data:/var/www/html/sites/all/modules/rit_faker
      - pacman-fhml_um_theme_demo-data:/var/www/html/sites/all/themes/fhml_um_theme_demo
    environment:
      IRODS_FRONTEND_ENV_VIRTUAL_HOST: frontend.${RIT_ENV}.rit.unimaas.nl
      IRODS_HOST: irods
      IRODS_ENV_RODS_PASSWORD: irods
      DWH_FRONTEND_ENV_VIRTUAL_HOST: dwh.${RIT_ENV}.rit.unimaas.nl
      CROSSREF_LOOKUP_HOST: crossref-lookup
      VIRTUAL_HOST: pacman.${RIT_ENV}.rit.unimaas.nl
      OLS_URL: http://ols.tst.rit.unimaas.nl
      LOGSTASH_TAGS: PACMAN
      JWT_SECRET: foobar
  irods:
    build: icat/
    hostname: irods
    ports:
      - "1247:1247"
      - "1248:1248"
    environment:
      RODS_PASSWORD: irods
      PGPASSWORD: foobar
      VIRTUAL_HOST: irods.${RIT_ENV}.rit.unimaas.nl
      IRODS_RESOURCE_HOST_DEB: ires
      IRODS_RESOURCE_HOST_RPM: ires-centos
      IRODS_INGEST_REMOVE_DELAY: 5m
      MIRTH_VALIDATION_CHANNEL: mirthconnect:6669
      MIRTH_METADATA_CHANNEL: mirthconnect:6670
      MIRTH_MDL_EXPORT_CHANNEL: fhml-srv024.unimaas.nl:6666
      LOGSPOUT: ignore
    networks:
      - default
      - common_default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - irods-secrets-data:/etc/secrets
      - irods-rules-data:/rules
      - irods-microservices-data:/microservices
  ires:
    build: ires/
    hostname: ires
    environment:
      RODS_PASSWORD: irods
      PGPASSWORD: foobar
      VIRTUAL_HOST: ires.${RIT_ENV}.rit.unimaas.nl
      IRODS_INGEST_REMOVE_DELAY: 5m
      MIRTH_VALIDATION_CHANNEL: mirthconnect:6669
      MIRTH_METADATA_CHANNEL: mirthconnect:6670
      MIRTH_MDL_EXPORT_CHANNEL: fhml-srv024.unimaas.nl:6666
      LOGSPOUT: ignore
    networks:
      - default
      - common_default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - irods-secrets-data:/etc/secrets
      - irods-rules-data:/rules
      - irods-microservices-data:/microservices
      - irods-helpers-data:/helpers
    # Required for CIFS mounting. cap-add not enough in Windows for some reason.
    privileged: true
  ires-centos:
    build: ires-centos/
    hostname: ires-centos
    environment:
      RODS_PASSWORD: irods
      PGPASSWORD: foobar
      VIRTUAL_HOST: ires-centos.${RIT_ENV}.rit.unimaas.nl
      IRODS_INGEST_REMOVE_DELAY: 5m
      MIRTH_VALIDATION_CHANNEL: mirthconnect:6669
      MIRTH_METADATA_CHANNEL: mirthconnect:6670
      MIRTH_MDL_EXPORT_CHANNEL: fhml-srv024.unimaas.nl:6666
      LOGSPOUT: ignore
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - irods-secrets-data:/etc/secrets
      - irods-rules-data:/rules
      - irods-microservices-data:/microservices
      - irods-helpers-data:/helpers
    # Required for CIFS mounting. cap-add not enough in Windows for some reason.
    privileged: true
    networks:
      - default
      - common_default
  db:
    image: mysql:5.6
    hostname: db
    environment:
      MYSQL_DATABASE: pacman
      MYSQL_ROOT_PASSWORD: foobar
      LOGSPOUT: ignore
    volumes:
      - /etc/localtime:/etc/localtime:ro
  irods-db:
    image: postgres:9.4
    hostname: irods-db
    environment:
      POSTGRES_PASSWORD: foobar
      LOGSPOUT: ignore
    volumes:
      - /etc/localtime:/etc/localtime:ro
  irods-frontend:
    build: externals/irods-frontend/
    hostname: irods-frontend
    environment:
      VIRTUAL_HOST: frontend.${RIT_ENV}.rit.unimaas.nl
      PACMAN_HOST: http://pacman.${RIT_ENV}.rit.unimaas.nl
      LOGSPOUT: ignore
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - common_default
  davrods:
    build: externals/rit-davrods/
    environment:
      VIRTUAL_HOST: webdav.${RIT_ENV}.rit.unimaas.nl
      LOGSTASH_TAGS: DAVRODS
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - common_default
  metalnx:
    build: externals/rit-metalnx-web/
    hostname: metalnx
    environment:
      IRODS_HOST: irods
      IRODS_PORT: 1247
      IRODS_ZONE: nlmumc
      IRODS_USER: rods
      IRODS_PASS: irods
      VIRTUAL_HOST: metalnx.${RIT_ENV}.rit.unimaas.nl
      VIRTUAL_PORT: 8080
      LOGSTASH_TAGS: METALNX
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mirthconnect:
    build: mirthconnect/
    hostname: mirthconnect
    ports:
      - "8443:8443"
      - "6661-6671:6661-6671"
    environment:
      PGPASSWORD: foobar
      RIT_ENV: ${RIT_ENV}
      VIRTUAL_HOST: mirthconnect.${RIT_ENV}.rit.unimaas.nl
      LOGSPOUT: ignore
    networks:
      - default
      - oculus_default
      - common_default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mirthconnect-data:/opt/channels
  crossref-lookup:
    build: externals/crossref-lookup
    volumes:
      - crossref-lookup-data:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: crossref-lookup.${RIT_ENV}.rit.unimaas.nl
    networks:
      - default
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  oculus_default:
    external: true
  common_default:
    external: true
volumes:
  pacman-fhml_um_theme_demo-data: 
    external: true
  pacman-handsontable-data: 
    external: true
  pacman-islandora_ontology_autocomplete-data: 
    external: true
  pacman-islandora_crossref_lookup-data: 
    external: true
  pacman-pacman-data: 
    external: true
  pacman-rit_landing_page-data: 
    external: true
  pacman-rit_forms-data: 
    external: true
  pacman-rit_faker-data: 
    external: true
  irods-helpers-data: 
    external: true
  irods-microservices-data: 
    external: true
  irods-rules-data: 
    external: true
  mirthconnect-data: 
    external: true
  crossref-lookup-data: 
    external: true
  irods-secrets-data:
    external: true

